name: Workflow for testing action

on:
  pull_request:
    types:
      - closed
    

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Execute Scripts GitHub Flow
        uses: Rindrics/execute-scripts-github-flow@v0.0.5
        with:
          requiredLabel: needed-label
          baseBranch: master
          targetScriptListDir: scripts
