name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: "TODO to Issue"
        if: contains(github.ref, 'master')
        uses: "Rindrics/todo-to-issue-action@add-org"
        id: "todo"
        with:
          TOKEN: ${{ secrets.TODO_TO_ISSUE}}
