name: Workflow for testing action

on:
  push:
    branches:
      - master

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Execute Scripts GitHub Flow
        uses: Rindrics/execute-scripts-github-flow@v0.0.1     
        with:
          requiredLabel: needed-label
          baseBranch: master
          targetScriptListDir: scripts
