name: Check Needed Labels on Issue Close

on:
  issues:
    types:
      - closed

jobs:
  check-label:
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ubuntu-latest

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "`size/` label"
        uses: Rindrics/require-label-prefix@v0.0.7
        with:
          secret: ${{ github.TOKEN }}
          prefix: size
          addLabel: true
          defaultLabel: "size/needed"
