name: Print Webhook Event

on:
  push:
    paths:
      - master
  pull_request:

jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print Webhook Event
        run: |
          echo "Event payload:"
          echo '${{ toJson(github.event) }}'
          echo '${{ github.event_path }}'
      
