name: Print Webhook Event

on:
  push:
    paths:
      - master
  pull_request:

jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print Webhook Event
        run: |
          echo "Event payload:"
          echo '${{ toJson(github.event) }}'

      - name: Print Webhook Event Path
        run: |
          echo '${{ github.event_path }}'
          cat '${{ github.event_path }}'

      - name: Load from envvar directly
        run: |
          echo $GITHUB_EVENT_PATH
          
      
